# Generated by Django 4.0 on 2022-01-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('providerAbbr', models.CharField(max_length=2, unique=True)),
                ('providerName', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('iban', models.CharField(max_length=50)),
                ('bankname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('tagid', models.CharField(max_length=9, unique=True)),
                ('licenceYear', models.IntegerField()),
                ('tagProvider', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='tagProvider', to='tl2175app.provider')),
                ('tagProviderAbbr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagProviderAbbr', to='tl2175app.provider', to_field='providerAbbr')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.CharField(default='', max_length=4, primary_key=True, serialize=False)),
                ('stationName', models.CharField(max_length=50)),
                ('stationProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tl2175app.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('passid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stationRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tl2175app.station')),
                ('vehicleRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tl2175app.vehicle')),
            ],
        ),
    ]
