# Generated by Django 4.0 on 2021-12-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerAbbr', models.CharField(max_length=2)),
                ('providerName', models.CharField(max_length=13)),
                ('iban', models.CharField(max_length=50)),
                ('bankname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=50)),
                ('stationProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tl2175app.provider')),
            ],
        ),
    ]
