# Generated by Django 4.0 on 2021-12-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tl2175app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stations',
            new_name='Station',
        ),
    ]
