# Generated by Django 4.0.1 on 2022-01-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tl2175app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passes',
            name='stationRef',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='vehicleRef',
        ),
        migrations.RemoveField(
            model_name='station',
            name='stationProvider',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tagProvider',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tagProviderAbbr',
        ),
    ]
