# Generated by Django 4.0 on 2022-01-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl2175app', '0002_alter_station_stationprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stationProvider',
            field=models.CharField(max_length=50),
        ),
    ]
