# Generated by Django 4.0.1 on 2022-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl2175app', '0002_remove_passes_stationref_remove_passes_vehicleref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='passid',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
