# Generated by Django 4.0 on 2022-01-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tl2175app', '0003_alter_station_stationprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tl2175app.provider'),
        ),
    ]
