# Generated by Django 4.0 on 2022-01-03 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tl2175app', '0004_station_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='providerName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='fk',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tl2175app.provider'),
        ),
    ]
